name: Ouo Bypasser Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  bypass-job:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fix and Install Playwright Dependencies
      run: |
        sudo apt-get update
        # Menginstal paket pengganti libasound2 untuk Ubuntu terbaru
        sudo apt-get install -y libasound2t64
        # Install chromium dan sisa dependensi sistem lainnya
        python -m playwright install chromium
        python -m playwright install-deps chromium

    - name: Run Bypasser
      run: python bypass.py

    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bypass-results
        path: results/results.json
